# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gaming Academy
email: stanimir.georgiev_99@abv.bg
description: Don't be just a human, become a legend!
destination: docs
baseurl: "/Pro_Gaming_Academy" # the subpath of your site, e.g. /blog
# baseurl: ""


url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  stanimir-georgiev

# Build settings
future: true
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs
  - _assets
  - gulpfile.js
  - package.json
  - package-lock.json

navigation:
  - url: /academy
    text: About
    icon: fa-caret-down
    items:
      - url: /academy
        text: Academy
      - url: /trainers
        text: Trainers
      # - url: /questions
      #   text: Questions
  # - url: /blog
  #   text: Blog
  # - url: /trainings
  #   text: Trainings
  - url: /proteams
    text: Teams
  - url: /achievements
    text: Trophies
  - url: /contacts
    text: Contacts
  - url: /login
    text: Login
  - url: /register
    text: Register

game-navigation:
  - url: /league
    text: League of Legends
    logo: /images/league.png
  - url: /fortnite
    text: Fortnite Battle Royale
    logo: /images/fortnite.png
  - url: /cs
    text: Counter Strike - Global Offensive
    logo: /images/cs.png
  - url: /hearthstone
    text: Hearthstone - Heroes of Warcraft
    logo: /images/hs.png
  - url: /pubg
    text: Playerunknown's Battlegrounds
    logo: /images/pubg.png

social-media:
  - icon: fa-facebook-f
    url: https://www.facebook.com
  - icon: fa-twitter
    url: https://twitter.com
  - icon: fa-twitch
    url: https://www.twitch.tv
  - icon: fa-youtube
    url: https://www.youtube.com
  - icon: fa-instagram
    url: https://www.instagram.com

sponsorship:
  - image: /images/razer.png
    name: Razer
    url: https://www.razer.com
  - image: /images/A1.png
    name: A1
    url: https://www.a1.bg
  - image: /images/ea.png
    name: EA Sports
    url: https://www.easports.com
  - image: /images/ps4.png
    name: Playstation 4
    url: https://www.playstation.com